const dummyNotes = [
  {
    id: 1,
    title: "What is the significance of the Kesavananda Bharati case?",
    titleAuthor: "Priya Sharma",
    subject: "Polity",
    rating: 4.5,
    titleUseful: 12,
    answer:
      "The Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam, scelerisque ut, mollis sed, nonummy id, metus. Nullam accumsan lorem in dui. Cras ultricies mi eu turpis hendrerit fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia. Nam pretium turpis et arcu. Duis arcu tortor, suscipit eget, imperdiet nec, imperdiet iaculis, ipsum. Sed aliquam ultrices mauris. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Praesent adipiscing. Phasellus ullamcorper ipsum rutrum nunc. Nunc nonummy metus. Vestibulum volutpat pretium libero. Cras id dui. Aenean ut eros et nisl sagittis vestibulum. Nullam nulla eros, ultricies sit amet, nonummy id, imperdiet feugiat, pede. Sed lectus. Donec mollis hendrerit risus. Phasellus nec sem in justo pellentesque facilisis. Etiam imperdiet imperdiet orci. Nunc nec neque. Phasellus leo dolor, tempus non, auctor et, hendrerit quis, nisi. Curabitur ligula sapien, tincidunt non, euismod vitae, posuere imperdiet, leo. Maecenas malesuada. Praesent congue erat at massa. Sed cursus turpis vitae tortor. Donec posuere vulputate arcu. Phasellus accumsan cursus velit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed aliquam, nisi quis porttitor congue, elit erat euismod orci, ac",
    answerAuthor: "Ankit Verma",
    answerUseful: 8,
  },
  {
    id: 2,
    title: "Explain the importance of monsoon for Indian agriculture.",
    titleAuthor: "Ravi Kumar",
    subject: "Geography",
    rating: 4.0,
    titleUseful: 9,
    answer: "",
    answerAuthor: "",
    answerUseful: 0,
  },
  {
    id: 3,
    title: "Discuss the role of NGOs in disaster management.",
    titleAuthor: "Sneha Mehta",
    subject: "Society",
    rating: 4.7,
    titleUseful: 15,
    answer:
      "NGOs play a crucial role in all stages of disaster management: preparedness, response, recovery, and mitigation. They engage with local communities to raise awareness, conduct training programs, and develop disaster response plans. During disasters, NGOs provide emergency relief, medical aid, food, and shelter. Post-disaster, they assist in rehabilitation, rebuilding infrastructure, and psychological support. Their local presence ensures faster mobilization of resources and culturally sensitive interventions. NGOs also advocate for policy changes and disaster risk reduction strategies at regional and national levels.",
    answerAuthor: "Divya Joshi",
    answerUseful: 10,
  },
  {
    id: 4,
    title: "How does globalization affect Indian culture?",
    titleAuthor: "Arjun Patel",
    subject: "Society",
    rating: 3.8,
    titleUseful: 7,
    answer: "",
    answerAuthor: "",
    answerUseful: 0,
  },
  {
    id: 5,
    title: "Differentiate between Tropical Evergreen and Deciduous forests.",
    titleAuthor: "Pooja Yadav",
    subject: "Geography",
    rating: 4.2,
    titleUseful: 11,
    answer:
      "Tropical Evergreen forests are dense, multi-layered forests that remain green throughout the year due to consistent rainfall. Found mainly in the western slopes of the Western Ghats and northeastern India, they are home to a wide variety of flora and fauna. Trees like ebony, mahogany, and rosewood are common. Deciduous forests, on the other hand, shed their leaves in the dry season to conserve water. They are found in central and southern India, characterized by species like sal, teak, and bamboo. Deciduous forests are more accessible for human use compared to evergreen forests.",
    answerAuthor: "Rahul Sen",
    answerUseful: 6,
  },
  {
    id: 6,
    title: "Differentiate between Tropical Evergreen and Deciduous forests.",
    titleAuthor: "Pooja Yadav",
    subject: "Geography",
    rating: 4.2,
    titleUseful: 11,
    answer:
      "Tropical Evergreen forests are dense, multi-layered forests that remain green throughout the year due to consistent rainfall. Found mainly in the western slopes of the Western Ghats and northeastern India, they are home to a wide variety of flora and fauna. Trees like ebony, mahogany, and rosewood are common. Deciduous forests, on the other hand, shed their leaves in the dry season to conserve water. They are found in central and southern India, characterized by species like sal, teak, and bamboo. Deciduous forests are more accessible for human use compared to evergreen forests.",
    answerAuthor: "Rahul Sen",
    answerUseful: 6,
  },
  {
    id: 7,
    title: "Differentiate between Tropical Evergreen and Deciduous forests.",
    titleAuthor: "Pooja Yadav",
    subject: "Geography",
    rating: 4.2,
    titleUseful: 11,
    answer:
      "Tropical Evergreen forests are dense, multi-layered forests that remain green throughout the year due to consistent rainfall. Found mainly in the western slopes of the Western Ghats and northeastern India, they are home to a wide variety of flora and fauna. Trees like ebony, mahogany, and rosewood are common. Deciduous forests, on the other hand, shed their leaves in the dry season to conserve water. They are found in central and southern India, characterized by species like sal, teak, and bamboo. Deciduous forests are more accessible for human use compared to evergreen forests.",
    answerAuthor: "Rahul Sen",
    answerUseful: 6,
  },
  {
    id: 8,
    title: "Differentiate between Tropical Evergreen and Deciduous forests.",
    titleAuthor: "Pooja Yadav",
    subject: "Geography",
    rating: 4.2,
    titleUseful: 11,
    answer:
      "Tropical Evergreen forests are dense, multi-layered forests that remain green throughout the year due to consistent rainfall. Found mainly in the western slopes of the Western Ghats and northeastern India, they are home to a wide variety of flora and fauna. Trees like ebony, mahogany, and rosewood are common. Deciduous forests, on the other hand, shed their leaves in the dry season to conserve water. They are found in central and southern India, characterized by species like sal, teak, and bamboo. Deciduous forests are more accessible for human use compared to evergreen forests.",
    answerAuthor: "Rahul Sen",
    answerUseful: 6,
  },
  {
    id: 9,
    title: "Differentiate between Tropical Evergreen and Deciduous forests.",
    titleAuthor: "Pooja Yadav",
    subject: "Geography",
    rating: 4.2,
    titleUseful: 11,
    answer:
      "Tropical Evergreen forests are dense, multi-layered forests that remain green throughout the year due to consistent rainfall. Found mainly in the western slopes of the Western Ghats and northeastern India, they are home to a wide variety of flora and fauna. Trees like ebony, mahogany, and rosewood are common. Deciduous forests, on the other hand, shed their leaves in the dry season to conserve water. They are found in central and southern India, characterized by species like sal, teak, and bamboo. Deciduous forests are more accessible for human use compared to evergreen forests.",
    answerAuthor: "Rahul Sen",
    answerUseful: 6,
  },
  {
    id: 10,
    title: "Differentiate between Tropical Evergreen and Deciduous forests.",
    titleAuthor: "Pooja Yadav",
    subject: "Geography",
    rating: 4.2,
    titleUseful: 11,
    answer:
      "Tropical Evergreen forests are dense, multi-layered forests that remain green throughout the year due to consistent rainfall. Found mainly in the western slopes of the Western Ghats and northeastern India, they are home to a wide variety of flora and fauna. Trees like ebony, mahogany, and rosewood are common. Deciduous forests, on the other hand, shed their leaves in the dry season to conserve water. They are found in central and southern India, characterized by species like sal, teak, and bamboo. Deciduous forests are more accessible for human use compared to evergreen forests.",
    answerAuthor: "Rahul Sen",
    answerUseful: 6,
  },
  {
    id: 11,
    title: "Differentiate between Tropical Evergreen and Deciduous forests.",
    titleAuthor: "Pooja Yadav",
    subject: "Geography",
    rating: 4.2,
    titleUseful: 11,
    answer:
      "Tropical Evergreen forests are dense, multi-layered forests that remain green throughout the year due to consistent rainfall. Found mainly in the western slopes of the Western Ghats and northeastern India, they are home to a wide variety of flora and fauna. Trees like ebony, mahogany, and rosewood are common. Deciduous forests, on the other hand, shed their leaves in the dry season to conserve water. They are found in central and southern India, characterized by species like sal, teak, and bamboo. Deciduous forests are more accessible for human use compared to evergreen forests.",
    answerAuthor: "Rahul Sen",
    answerUseful: 6,
  },
  // Add more as needed
];

export default dummyNotes;
