export const subjects = {
  1: { name: "Ancient History", color: "primary" },
  2: { name: "Medieval History", color: "secondary" },
  3: { name: "Modern History", color: "success" },
  4: { name: "Post-Independence History", color: "danger" },
  5: { name: "World History", color: "warning" },
  6: { name: "Physical Geography", color: "info" },
  7: { name: "Indian Geography", color: "primary" },
  8: { name: "World Geography", color: "secondary" },
  9: { name: "Economic Geography", color: "success" },
  10: { name: "Indian Polity", color: "danger" },
  11: { name: "Governance & Public Policy", color: "warning" },
  12: { name: "Political Theories", color: "info" },
  13: { name: "International Law & Organizations", color: "primary" },
  14: { name: "Indian Economy", color: "secondary" },
  15: { name: "Macroeconomics & Microeconomics", color: "success" },
  16: { name: "Banking & Finance", color: "danger" },
  17: { name: "International Economy", color: "warning" },
  18: { name: "Space & Defense Technology", color: "info" },
  19: { name: "Biotechnology & Health", color: "primary" },
  20: { name: "Artificial Intelligence & IT", color: "secondary" },
  21: { name: "Basic & Applied Science", color: "success" },
  22: { name: "Climate Change", color: "danger" },
  23: { name: "Biodiversity & Conservation", color: "warning" },
  24: { name: "Environmental Laws & Treaties", color: "info" },
  25: { name: "Disaster Management", color: "primary" },
  26: { name: "India’s Bilateral Relations", color: "secondary" },
  27: { name: "Global Institutions", color: "success" },
  28: { name: "Geopolitical Issues", color: "danger" },
  29: { name: "Foreign Policies & Agreements", color: "warning" },
  30: { name: "Ethical Theories", color: "info" },
  31: { name: "Public Administration Ethics", color: "primary" },
  32: { name: "Philosophy & Thinkers", color: "secondary" },
  33: { name: "Case Studies & Real-Life Applications", color: "success" },
  34: { name: "Current Affairs", color: "danger" },
  35: { name: "Government Schemes & Policies", color: "warning" },
  36: { name: "Social Issues", color: "info" },
  37: { name: "Indian Society & Culture", color: "primary" },
  38: { name: "Internal Security", color: "secondary" },
  39: { name: "Science & Disaster Management", color: "success" },
  40: { name: "Indian Art & Culture", color: "danger" },
  41: { name: "Agriculture & Food Security", color: "warning" },
  42: { name: "Social Justice & Welfare", color: "info" },
};
